version: '3'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose Nuxt.js app on port 3000
      - "5173:5173"
    environment:
      - .env
     
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf  # Use custom Nginx configuration
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - nuxt-app  # Ensure the Nuxt.js app starts before Nginx
    environment:
     - VITE_API_URL=http://nuxt-app:3000
    
